remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
url: 'http://ei7trg.ie'
name: EI7TRG
description: 'Tipperary Amateur Radio Group'
